services:
  postgres:
    image: postgres:latest
    container_name: dwh_postgres
    environment:
      POSTGRES_USER: ${DBT_USER}
      POSTGRES_PASSWORD: ${DBT_PASSWORD}
      POSTGRES_DB: dwh
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DBT_USER} -d dwh"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
  pgadmin_data: